const lcuImage = require("../assets/images/unis/lcu.png");
const oouImage = require("../assets/images/unis/oou.png");
const lasuImage = require("../assets/images/unis/lasu.png");

export const universities = [
  {
    id: 1,
    name: "LCU",
    location: "Ibadan, Oyo",
    image: lcuImage,
  },
  {
    id: 2,
    name: "OOU",
    location: "Ago-iwoye, Ogun",
    image: oouImage,
  },
  {
    id: 3,
    name: "Tasued",
    location: "Ijebu ode, Ogun",
    image: require("../assets/images/unis/tasued.png"),
  },
  {
    id: 4,
    name: "Unilag",
    location: "Yaba, Lagos",
    image: require("../assets/images/unis/unilag.png"),
  },
  {
    id: 5,
    name: "LASU",
    location: "Ojo, Lagos",
    image: lasuImage,
  },
  { id: 6, name: "OAU", location: "Ile-Ife, Osun" },
  { id: 7, name: "AAP", location: "Abeokuta, Ogun", image: lcuImage },
  { id: 8, name: "LasuTech", location: "Ikorodu, Lagos" },
  { id: 9, name: "YabaTech", location: "Yaba, Lagos", image: lcuImage },
  { id: 10, name: "Convenant", location: "Ile, Ogun", image: lcuImage },
  { id: 11, name: "BabCok", location: "Ile, Ogun", image: lcuImage },
  { id: 12, name: "IMSU", location: "Ile, Ogun", image: lcuImage },
  { id: 13, name: "ABSU", location: "Ile, Ogun", image: lcuImage },
  { id: 14, name: "EBSU", location: "Ile, Ogun", image: lcuImage },
  { id: 15, name: "Afe Babalola", location: "Ile, Ogun", image: lcuImage },
  { id: 16, name: "Abuad", location: "Ile, Ogun", image: lcuImage },
  { id: 17, name: "Kola-Daisi", location: "Ile, Ogun", image: lcuImage },
  { id: 18, name: "Ibadan Poly", location: "Ile, Ogun", image: lcuImage },
  { id: 19, name: "UI", location: "Ile, Ogun", image: lcuImage },
  { id: 20, name: "Uni-Illorin", location: "Ile, Ogun", image: lcuImage },
  { id: 21, name: "Madonna", location: "Ile, Ogun", image: lcuImage },
  { id: 22, name: "Nile", location: "Ile, Ogun", image: lcuImage },
  { id: 23, name: "Base", location: "Ile, Ogun", image: lcuImage },
  { id: 24, name: "Funai", location: "Ile, Ogun", image: lcuImage },
  {
    id: 25,
    name: "Caritas University",
    location: "Ile, Ogun",
    image: lcuImage,
  },
  { id: 26, name: "ChrisLand", location: "Ile, Ogun", image: lcuImage },
  { id: 27, name: "Paul University", location: "Ile, Ogun" },
  { id: 28, name: "Veritas", location: "Ile, Ogun", image: lcuImage },
  { id: 29, name: "FUTA", location: "Ile, Ogun", image: lcuImage },
  { id: 30, name: "FUTO", location: "Ile, Ogun", image: lcuImage },
  { id: 31, name: "Redeemer's University", location: "Ede" },
  {
    id: 32,
    name: "Pan-Atlantic University",
    location: "Lagos",
    image: lcuImage,
  },
];
